### PR TITLE
Fix db datapoints and add improved logging

### LINKED ISSUE #38: Fix the data being stored to db
- The stat points created, completed, failed, and deleted are not working properly
- remove the active stat point

### PR DESCRIPTION
**Pull request by avinal**
- Remove active datapoint
- add klog for logging
- Fixes #38

### CODE REVIEW

File: pkg/controllers/mkstaskrun/controller.go [hunk 1]
```diff
@@ -64,57 +64,56 @@ func NewController(kubeclientset kubernetes.Interface,
...
+		klog.Infof("\tMksTaskRun %s created: %s\n", ttr.GetName(), ttr.GetUID())
 	}
-
-	fmt.Printf("Successfully created Tekton TaskRun: %s\n", ttr.Name)
 	c.queue.Add(obj)
 }
 
 func (c *Controller) updateController(oldObj, newObj interface{}) {
-	fmt.Println("MksTaskRun has been updated")
+	klog.Info("\tUpdate mkstask was called\n")
```
Comment (ramessesii2) [inline pkg/controllers/mkstaskrun/controller.go]: `` Update mkstaskrun``

**Review by ramessesii2 — CHANGES_REQUESTED** [review]
